---

default: &default
  primary_user: &primary_user
    username: <%= ENV['CUCUMBER_PRIMARY_USERNAME'] || 'local' %>
    password: <%= ENV['CUCUMBER_PRIMARY_PASSWORD'] || 'development' %>
    given_name: <%= ENV['CUCUMBER_PRIMARY_GIVEN_NAME'] || ENV['CUCUMBER_PRIMARY_USERNAME'] || 'local' %>
    bank: <%= ENV['CUCUMBER_PRIMARY_BANK'] || 'Meridian Bank, National Association' %>
  signer_advances_user:
    username: <%= ENV['CUCUMBER_SIGNER_ADVANCES_USERNAME'] || 'extra-signer' %>
    password: <%= ENV['CUCUMBER_SIGNER_ADVANCES_PASSWORD'] || 'development' %>
  non_signer_advances_user:
    username: <%= ENV['CUCUMBER_NON_SIGNER_ADVANCES_USERNAME'] || 'local-non-signer' %>
    password: <%= ENV['CUCUMBER_NON_SIGNER_ADVANCES_PASSWORD'] || 'development' %>
  intranet_user: &intranet_user
    username: <%= ENV['CUCUMBER_INTRANET_USERNAME'] || 'local' %>
    password: <%= ENV['CUCUMBER_INTRANET_PASSWORD'] || 'development' %>
    bank: <%= ENV['CUCUMBER_INTRANET_BANK'] || 'Central Valley Community Bank' %>
  extranet_user:
    username: <%= ENV['CUCUMBER_EXTRANET_USERNAME'] || 'extra' %>
    password: <%= ENV['CUCUMBER_EXTRANET_PASSWORD'] || 'development' %>
  access_manager:
    username: <%= ENV['CUCUMBER_ACCESS_MANAGER_USERNAME'] || 'extra-chaste-access' %>
    password: <%= ENV['CUCUMBER_ACCESS_MANAGER_PASSWORD'] || 'development' %>
  deletable:
    username: <%= ENV['CUCUMBER_DELETABLE_USERNAME'] || 'extra-chaste-delete' %>
    password: <%= ENV['CUCUMBER_DELETABLE_PASSWORD'] || 'development' %>
  resetable:
    username: <%= ENV['CUCUMBER_RESETABLE_USERNAME'] || 'extra-chaste-reset' %>
    password: <%= ENV['CUCUMBER_RESETABLE_PASSWORD'] || 'development' %>
  read_only_access_manager:
    username: <%= ENV['CUCUMBER_ACCESS_MANAGER_READ_USERNAME'] || 'extra-chaste-access-read-only' %>
    password: <%= ENV['CUCUMBER_ACCESS_MANAGER_READ_PASSWORD'] || 'development' %>
  expired:
    username: <%= ENV['CUCUMBER_EXPIRED_USERNAME'] || 'extra-expired' %>
    password: <%= ENV['CUCUMBER_EXPIRED_PASSWORD'] || 'development' %>
  password_changable:
    username: <%= ENV['CUCUMBER_PASSWORD_CHANGE_USERNAME'] || 'extra-password' %>
    password: <%= ENV['CUCUMBER_PASSWORD_CHANGE_PASSWORD'] || 'development' %>
  extranet_no_role:
    username: <%= ENV['CUCUMBER_EXTRANET_NOROLE_USERNAME'] || 'extra-chaste-norole' %>
    password: <%= ENV['CUCUMBER_EXTRANET_NOROLE_PASSWORD'] || 'development' %>
  offsite:
    username: <%= ENV['CUCUMBER_OFFSITE_USERNAME'] || 'local-offsite' %>
    password: <%= ENV['CUCUMBER_OFFSITE_PASSWORD'] || 'development' %>
  first_time:
    username: <%= ENV['CUCUMBER_OFFSITE_USERNAME'] || 'extra-chaste-first-time' %>
    password: <%= ENV['CUCUMBER_OFFSITE_PASSWORD'] || 'development' %>
  advances_disabled:
    username: <%= ENV['CUCUMBER_OFFSITE_USERNAME'] || 'quick-advance-disabled' %>
    password: <%= ENV['CUCUMBER_OFFSITE_PASSWORD'] || 'development' %>
  dual_signer:
    username: <%= ENV['CUCUMBER_DUAL_SIGNER_USERNAME'] || 'dual-signer-required' %>
    password: <%= ENV['CUCUMBER_DUAL_SIGNER_PASSWORD'] || 'development' %>
  extended_info:
    username: <%= ENV['CUCUMBER_EXTENDED_INFO_USERNAME'] || 'local-extended-info' %>
    password: <%= ENV['CUCUMBER_EXTENDED_INFO_PASSWORD'] || 'development' %>
  collateral_signer:
    username: <%= ENV['CUCUMBER_SIGNER_COLLATERAL_USERNAME'] || 'extra-collateral-signer' %>
    password: <%= ENV['CUCUMBER_SIGNER_COLLATERAL_PASSWORD'] || 'development' %>
  securities_signer:
    username: <%= ENV['CUCUMBER_SIGNER_SECURITIES_USERNAME'] || 'extra-securities-signer' %>
    password: <%= ENV['CUCUMBER_SIGNER_SECURITIES_PASSWORD'] || 'development' %>
  valid_password: <%= ENV['CUCUMBER_VALID_PASSWORD'] || '123Abcd3!' %>

local:
  <<: *default
  primary_user:
    <<: *primary_user
    bank: <%= ENV['CUCUMBER_PRIMARY_BANK'] || 'Wells Faygo' %>
  intranet_user:
    <<: *intranet_user
    bank: <%= ENV['CUCUMBER_PRIMARY_BANK'] || 'Chaste Manhattan' %>
dev:
  <<: *default

test:
  <<: *default

production:
  <<: *default

# insert configs once known
#qa:
#  app_host: 'qa.foo.com'
#  user1:
#    username:
#    password:
#
#staging:
#  app_host: 'stg.foo.com'
#  user1:
#    username:
#    password:
#
#production:
#  app_host: 'www.foo.com'
#  user1:
#    username:
#    password: